#ifndef ELOGY_MILK_DBG_H_
#define ELOGY_MILK_DBG_H_

#include "types.h"

typedef enum
{
	FSM_STATE_INIT					= 0x00,
	FSM_STATE_STANDBY				= 0x01,
	FSM_STATE_FIRST_HEATING			= 0x02,
	FSM_STATE_HEATING				= 0x03,
	FSM_STATE_READY_TO_BREW			= 0x04,
	FSM_STATE_BREWING				= 0x05,
	FSM_STATE_PRESS_DISCHARGE		= 0x06,
	FSM_STATE_STEAMING				= 0x07,
	FSM_STATE_DESCALING				= 0x08,
	FSM_STATE_RINSING				= 0x09,
	FSM_STATE_FAULT					= 0x0A,
	FSM_STATE_CYCLING				= 0x0B,
	FSM_STATE_AFTER_LOWPOWER		= 0x0C,
	FSM_STATE_FACTORY_RESET			= 0x0D,
	FSM_STATE_RINSING_RUN			= 0x0E,
	FSM_STATE_DESCALING_RUN			= 0x0F,
	FSM_STATE_DESCALING_WAIT		= 0x10,
	FSM_STATE_DESCALING_PAUSE		= 0x11,
	FSM_STATE_RINSING_WAIT			= 0x12,
	FSM_STATE_RINSING_PAUSE			= 0x13,
	FSM_STATE_HEATING_DESCALE		= 0x14,
	FSM_STATE_PRESSURE_TEST_WAIT	= 0x15,
	FSM_STATE_HEATING_HIGH_PRESSURE	= 0x16,
	FSM_STATE_PRESSURE_TEST_RUN		= 0x17,
	FSM_STATE_EROGATION_PAUSE		= 0x18,
	FSM_STATE_DOSE_PROGRAMMING		= 0x19,
	FSM_STATE_COOLING				= 0x1A,
	FSM_STATE_BLE_PAIRING			= 0x1B,
	
	FSM_MAX_STATE
} FSM_StateID_t;

#endif // ELOGY_MILK_DBG_H_