EXTRA_COMPONENT_DIRS += $(IOT_SOLUTION_PATH)/components
EXTRA_COMPONENT_DIRS += $(IOT_SOLUTION_PATH)/components/bus
EXTRA_COMPONENT_DIRS += $(IOT_SOLUTION_PATH)/components/display
EXTRA_COMPONENT_DIRS += $(IOT_SOLUTION_PATH)/components/gui
EXTRA_COMPONENT_DIRS += $(IOT_SOLUTION_PATH)/components/boards
